apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-node-ready-tracker
  namespace: karpenter
  labels:
    app: karpenter-node-ready-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karpenter-node-ready-tracker
  template:
    metadata:
      labels:
        app: karpenter-node-ready-tracker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
      serviceAccountName: karpenter-node-ready-tracker
      automountServiceAccountToken: true
      containers:
      - name: karpenter-node-ready-tracker
        image: <Update with Container Image>
        resources:
          requests:
            cpu: "20"
            memory: "50Gi"
          limits:
            cpu: "20"
            memory: "50Gi"
        volumeMounts:
        - name: data-volume
          mountPath: /app
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      - key: dedicated
        operator: Equal
        value: karpenter
      volumes:
      - name: data-volume
        emptyDir: {}
      priorityClassName: system-cluster-critical
