---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-node-ready-tracker
  namespace: karpenter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpenter-node-ready-tracker
  namespace: karpenter
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["karpenter.sh"]
  resources: ["nodeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-node-ready-tracker
  namespace: karpenter
subjects:
- kind: ServiceAccount
  name: karpenter-node-ready-tracker
  namespace: karpenter
roleRef:
  kind: ClusterRole
  name: karpenter-node-ready-tracker
  apiGroup: rbac.authorization.k8s.io